name: airtime_purchase_app
description: A demo project based off of the Falcorp assessment.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  intl: ^0.17.0
  shimmer: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  lottie: ^1.2.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/ic_eezi_airtime.png
    - assets/icons/ic_provider_cell.png
    - assets/icons/ic_provider_mtn.png
    - assets/icons/double-chevron.png
    - assets/icons/ic_provider_telkom.png
    - assets/icons/ic_provider_virgin.png
    - assets/icons/ic_provider_vodacom.png
    - assets/icons/ic_provider_world_call.png
    - assets/images/flash_guy.png
    - assets/images/icon.jpeg
    - assets/images/flash_bg.jpeg
    - assets/anim/busy.json
    - assets/anim/sales.json
    - assets/anim/deals.json
    
